// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noeyoljpeemfnlubhlas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZXlvbGpwZWVtZm5sdWJobGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTQwMDEsImV4cCI6MjA2ODc3MDAwMX0.Qoloc5uclKfWEyQAN51BSkd53_7AL2fRHNkYgV47ehI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});